/* 
* Important! 
* This file is automatically generated with python utils/genops.py
* Do not modify it!
*/ 

#ifndef WFOPERATOR_H
#define WFOPERATOR_H

const unsigned OP_ADD = 0xf5407fe5;
const unsigned OP_SUB = 0xd5153ca0;
const unsigned OP_DIV = 0x65f72102;
const unsigned OP_MUL = 0x7881bffd;
const unsigned OP_POW = 0xf7c35220;
const unsigned OP_SIN = 0x759d7c9f;
const unsigned OP_COS = 0xab8fbabb;
const unsigned OP_TAN = 0xbb7a7f15;
const unsigned OP_COT = 0x19fb330b;
const unsigned OP_LN = 0x42915e0b;
const unsigned OP_SH = 0x6c00f189;
const unsigned OP_CH = 0xc4315587;
const unsigned OP_TH = 0xf0c16625;
const unsigned OP_CTH = 0x6ec624d;
const unsigned OP_LOG = 0x7b0741e5;
const unsigned OP_EXP = 0x7ed16325;
const unsigned OP_DRV = 0x19c7d28e;

const char *optostr(unsigned hash);

#endif /* WFOPERATOR_H */
