/* 
* Important! 
* This file is automatically generated with python utils/genops.py
* Do not modify it!
*/ 

#include <wolfram/operators.h>


const char *optostr(unsigned hash)
{
        switch (hash) {
        case OP_ADD: 
                return "+";
        case OP_SUB: 
                return "-";
        case OP_DIV: 
                return "/";
        case OP_MUL: 
                return "*";
        case OP_POW: 
                return "^";
        case OP_SIN: 
                return "sin";
        case OP_COS: 
                return "cos";
        case OP_TAN: 
                return "tg";
        case OP_COT: 
                return "ctg";
        case OP_LN: 
                return "ln";
        case OP_SH: 
                return "sh";
        case OP_CH: 
                return "ch";
        case OP_TH: 
                return "th";
        case OP_CTH: 
                return "cth";
        case OP_LOG: 
                return "log";
        case OP_EXP: 
                return "exp";
        case OP_DRV: 
                return "drv";
        default:
                return nullptr;
}
}
